### ISSUE TITLE
你好，作者大大！

### ISSUE THREAD

**Issue by GragonWing** [zerzerzerz/IS303#1]
我也对Microsoft的开源项目muzic感兴趣，不过呢，这个使用这个项目的时候存在一些疑问，不知可否向你咨询，就是songmass项目中的ground truth文件是如何生成的呢？还有，推理出来的文件是放在/data_org/processed/下面吗？
因为我没有找到你的联系方式，所以采用这种方法来向你提问，如果你能解惑，非常感谢！

**Comment by zerzerzerz** [comment]
> 

你好！我使用这个项目本来是想生成melody然后放到我们的课程设计，但我跑完之后不太清楚怎么把这份代码里面的midi转为可播放的形式，再加上服务器突然坏了，导致我后面没有继续去看这个而是转而去寻找其他code了。
关于ground truth文件，因为我本来打算生成音乐的，所以没怎么关注evaluation的部分。。。抱歉
但是关于inference，我跑了一次melody的inference，需要自己指定输出的位置，比如在`infer_melody.sh`文件中添加`--results-path ./my_output/infer_melody`，就能在执行完`infer_melody.sh`找到对应的输出了，希望能对你有所帮助

**Comment by GragonWing** [comment]
非常感谢你的帮助！！！
在执行完`inter_melody.sh`后生成了`generate-valid.txt`，然后我按照你在issues中与另外一位的讨论中，他提供了一段代码来将生成的midi转化成真正的midi文件，但是我在引用的时候遇到点转化格式的问题，我看到你在下面有提到跑通了，请问你可以提供一下思路或者是演示或者是你跑通成功的处理代码吗？

**Comment by GragonWing** [comment]
非常感谢你的帮助！！！

在执行完inter_melody.sh后生成了generate-valid.txt，然后我按照你在issues中与另外一位的讨论中，他提供了一段代码来将生成的midi转化成真正的midi文件，但是我在引用的时候遇到点转化格式的问题，报错如下，我看到你在下面有提到跑通了，请问你可以提供一下思路或者是演示或者是你跑通成功的处理代码吗？

我的使用方法是：
在函数下面添加了这些代码
`f=open('generate-valid.txt',encoding = 'utf-8').read()`
`midi_list2file(f)`
报错信息：
`Traceback (most recent call last):`
  `File "midi.py", line 37, in <module>`
    `midi_list2file(f)`
  `File "midi.py", line 22, in midi_list2file`
    `note_number = int(note_list[idx])`
`ValueError: invalid literal for int() with base 10: 'S'`

如果你能解惑，非常感谢！

**Comment by zerzerzerz** [comment]
> 

我是执行的下面的代码来生成midi文件
```
import pretty_midi


def midi_list2file(note_list):
    # Create a PrettyMIDI object
    cello_c_chord = pretty_midi.PrettyMIDI()
    # Create an Instrument instance for a cello instrument
    cello_program = pretty_midi.instrument_name_to_program('Cello')
    cello = pretty_midi.Instrument(program=cello_program)
    # Iterate over note names, which will be converted to note number later
    st_tm = 0
    idx = 0
    while idx < len(note_list):
        while note_list[idx] in ("[align]", "[sep]"):
            idx += 1
            if idx >= len(note_list):
                break
        if idx >= len(note_list):
            break
        # Create a Note instance for this note, starting at 0s and ending at .5s
        print(note_list[idx], note_list[idx + 1])
        note_number = int(note_list[idx])
        duration = float(int(note_list[idx + 1]) - 128) * 0.5  # 120bpm,1/4音符一拍
        if note_number < 128:
            print(note_number, st_tm, duration + st_tm)
            note = pretty_midi.Note(velocity=100, pitch=note_number, start=st_tm, end=duration + st_tm)
            cello.notes.append(note)
        st_tm += duration
        idx += 2

    # Add the cello instrument to the PrettyMIDI object
    cello_c_chord.instruments.append(cello)
    # Write out the MIDI data
    cello_c_chord.write('cello-C-chord.mid')


if __name__ == "__main__":
    melody_path = "melody.txt"
    with open(melody_path,'r') as f:
        melody = f.read()
        note_list = melody.split(' ')
        print(note_list)
    midi_list2file(note_list)
```
然后`melody.txt`如下
```
64 140 62 132 [sep] 128 132 62 144 [sep] 128 144 61 140 65 132 64 144 [sep] 128 144 60 136 60 132 59 140 [sep] 128 144 52 132 55 132 55 130 57 142 59 140 60 136 [sep] 128 132 63 136 128 132 64 136 60 142 62 132 128 132 62 144 [sep]
```
然后就能生成midi文件了，虽然听起来怪怪的，因为这份转换代码，如你所见，我也是用的那个issue下面的，所以也不能确定真正的结果是怎样的。

**Comment by zerzerzerz** [comment]
> 非常感谢你的帮助！！！
> 
> 在执行完inter_melody.sh后生成了generate-valid.txt，然后我按照你在issues中与另外一位的讨论中，他提供了一段代码来将生成的midi转化成真正的midi文件，但是我在引用的时候遇到点转化格式的问题，报错如下，我看到你在下面有提到跑通了，请问你可以提供一下思路或者是演示或者是你跑通成功的处理代码吗？
> 
> 我的使用方法是： 在函数下面添加了这些代码 `f=open('generate-valid.txt',encoding = 'utf-8').read()` `midi_list2file(f)` 报错信息： `Traceback (most recent call last):` `File "midi.py", line 37, in <module>` `midi_list2file(f)` `File "midi.py", line 22, in midi_list2file` `note_number = int(note_list[idx])` `ValueError: invalid literal for int() with base 10: 'S'`
> 
> 如果你能解惑，非常感谢！

我也只是这么猜测的哈，因为之后就去搞别的了，这个项目也没有继续研究下去，抱歉

**Comment by GragonWing** [comment]
非常感谢你能如此及时的解答我的疑惑！谢谢你的帮助，接下来我会自己摸索的，谢谢！
